version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
        - db
  db:
    container_name: postgres-horas-complementares
    image: postgres:13
    environment:
      - POSTGRES_DB=horas_complementares
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PGDATA=data/postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "15433:5432"

volumes:
    postgres-db:
        driver: local