# Generated by Django 4.1.7 on 2023-03-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_hours', '0003_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycourse',
            old_name='maximun_hours',
            new_name='maximum_hours',
        ),
    ]
