# Generated by Django 4.1.7 on 2023-04-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_hours', '0004_rename_maximun_hours_activitycourse_maximum_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='file_data',
            field=models.BinaryField(null=True, verbose_name='Arquivo | Binário'),
        ),
    ]
