# Generated by Django 4.1.7 on 2023-04-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional_hours', '0005_useractivity_file_useractivity_file_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycourse',
            old_name='activity',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='activitycourse',
            old_name='course',
            new_name='course_id',
        ),
    ]
