# Generated by Django 4.1.7 on 2023-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_hours', '0007_rename_activity_id_activitycourse_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='É válido'),
        ),
    ]
