# Generated by Django 4.1.7 on 2023-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_hours', '0008_alter_useractivity_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='file_data',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='file',
            field=models.TextField(null=True, verbose_name='Arquivo'),
        ),
    ]
