### GET
GET http://127.0.0.1:8000/api/activity/

### GET
GET http://127.0.0.1:8000/api/activity/1/

### POST
POST http://127.0.0.1:8000/api/activity/
Content-Type: application/json

{
  "name":  "Teste",
  "description": "Teste"
}

### PUT
PUT http://127.0.0.1:8000/api/activity/1/
Content-Type: application/json

{
  "name":  "Novo nome",
  "description": "Nova descrição"
}

### DELETE
DELETE http://127.0.0.1:8000/api/activity/2/
