# Generated by Django 4.1.7 on 2023-04-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('additional_hours', '0009_remove_useractivity_file_data_and_more'),
        ('users', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='additional_hours.course', verbose_name='Curso'),
        ),
    ]
